---
- hosts: all
  remote_user: root
  vars_files:
    - variables/all.yml

  tasks:
    - name: Run {{task_file}} tasks
      include_tasks: tasks/{{task_file}}
      loop:
        - user.yml
        - shell.yml
        - nginx.yml
        - code_server.yml
        - docker.yml
      loop_control:
        loop_var: task_file
