- name: Add Google apt Key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: APT repo for chrome
  apt_repository:
    repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main

- name: Install chrome
  apt:
    state: latest
    cache_valid_time: "{{apt_cache_delay}}"
    name: google-chrome-stable

- name: Install chromedriver
  unarchive:
    src: https://chromedriver.storage.googleapis.com/{{chromedriver_version}}/chromedriver_linux64.zip
    dest: ~{{username}}/bin/
    remote_src: yes
    creates: ~{{username}}/bin/chromedriver
  become: yes
  become_user: "{{username}}"
