- name: Create code_server data directory
  file:
    path: "{{code_server_data_path}}"
    mode: "700"
    state: directory
  become: yes
  become_user: "{{username}}"

- name: Download & unpack code-server
  unarchive:
    src: https://github.com/cdr/code-server/releases/download/{{code_server_version}}/code-server-{{code_server_version}}-linux-x86_64.tar.gz
    dest: ~{{username}}/bin
    remote_src: yes
    creates: ~{{username}}/bin/code-server-{{code_server_version}}-linux-x86_64
  become: yes
  become_user: "{{username}}"

- name: Code Server symlink
  file:
    src: ~{{username}}/bin/code-server-{{code_server_version}}-linux-x86_64
    dest: ~{{username}}/bin/code-server
    state: link
  become: yes
  become_user: "{{username}}"

- name: Code Server service
  template:
    src: templates/code_server/code-server.service.j2
    dest: /lib/systemd/system/code-server.service
    mode: 0644
  vars:
    code_server_path: "/home/{{username}}/bin/code-server"
    host: "{{code_server_remote_host}}"
    port: "{{code_server_local_port}}"

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Start Code Server service
  service:
    name: code-server
    enabled: yes
    state: restarted

- name: Restart nginx
  service:
    name: nginx
    state: restarted

- name: NGinx reverse proxy for Code Server
  template:
    src: templates/nginx/site.conf.j2
    dest: /etc/nginx/sites-available/code-server.conf
    mode: 0600
  vars:
    host: "{{code_server_remote_host}}"
    port: "{{code_server_local_port}}"

- name: NGinx config symlink
  file:
    src: /etc/nginx/sites-available/code-server.conf
    dest: /etc/nginx/sites-enabled/code-server.conf
    state: link

- name: Create letsencrypt certificate
  shell: certbot --nginx -n -m {{ letsencrypt_email }} --agree-tos -d {{ code_server_remote_host }} --redirect

- name: Restart nginx
  service:
    name: nginx
    state: restarted
