- name: Create code directory
  file:
    path: "{{code_directory}}"
    mode: "700"
    state: directory
  become: yes
  become_user: "{{username}}"

- name: Install dev requirements
  homebrew:
    state: latest
    name: ["ffmpeg", "imagemagick", "heroku", "chromedriver"]
