- name: Install codeserver
  homebrew:
    state: latest
    name: codeserver

- name: NGinx reverse proxy for Code Server
  template:
    src: templates/nginx/site.conf.j2
    dest: /etc/nginx/sites-available/code-server.conf
    mode: 0600
  vars:
    host: "{{code_server_remote_host}}"
    port: "{{code_server_local_port}}"

- name: NGinx config symlink
  file:
    src: /etc/nginx/sites-available/code-server.conf
    dest: /etc/nginx/sites-enabled/code-server.conf
    state: link

- name: Create letsencrypt certificate
  shell: certbot --nginx -n -m {{ letsencrypt_email }} --agree-tos -d {{ code_server_remote_host }} --redirect

- name: Restart nginx
  service:
    name: nginx
    state: restarted
