- name: Install asdf
  homebrew:
    state: latest
    name: asdf

- name: Install asdf Erlang plugin
  command: "asdf plugin add erlang"
  args:
    creates: ~{{username}}/.asdf/plugins/erlang

- name: Install asdf Elixir plugin
  command: "asdf plugin add elixir"
  args:
    creates: ~{{username}}/.asdf/plugins/elixir

- name: Install Erlang {{erlang_version}}
  command: "asdf install erlang {{erlang_version}} && asdf global erlang {{erlang_version}}"
  args:
    creates: ~{{username}}/.asdf/installs/erlang/{{erlang_version}}

- name: Install Elixir {{elixir_version}}
  command: "asdf install elixir {{elixir_version}} && asdf global elixir {{elixir_version}}"
  args:
    creates: ~{{username}}/.asdf/installs/elixir/{{elixir_version}}

- name: asdf reshim
  command: "asdf reshim"
