- name: Install nginx & certbot
  homebrew:
    state: latest
    name: ["nginx", "certbot"]

- name: Copy nginx launchctl script
  become: yes
  template:
    src: templates/launchctl/homebrew.mxcl.nginx.plist.j2
    dest: "{{launchagents_path}}/{{launchagents_service_prefix}}.nginx.plist"
    mode: "644"

- name: Load nginx service
  become: yes
  community.general.launchd:
    name: "{{launchagents_service_prefix}}.nginx"
    state: started
