- name: APT repo for certbot
  apt_repository:
    repo: "ppa:certbot/certbot"

- name: Install nginx & certbot
  apt:
    state: latest
    cache_valid_time: "{{apt_cache_delay}}"
    name: ["nginx", "python-certbot-nginx"]

- name: Start nginx
  service:
    name: nginx
    state: started
