- name: Install PostgresQL
  homebrew:
    state: present
    name: postgresql

- name: Copy postgresql launchctl script
  become: yes
  template:
    src: templates/launchctl/homebrew.mxcl.postgresql.plist.j2
    dest: /Library/LaunchAgents/homebrew.mxcl.postgresql.plist
    mode: "644"

- name: chmod postgres data dir
  become: yes
  file:
    path: "{{brew_path}}/var/postgres"
    recurse: yes
    owner: "{{username}}"
    group: admin
    mode: "0750"

- name: Load postgres service
  become: yes
  community.general.launchd:
    name: homebrew.mxcl.postgresql
    state: started
