- name: Installing zsh, git, autojump, fzf, direnv & tmux
  homebrew:
    state: latest
    name: ["zsh", "git", "autojump", "fzf", "direnv", "tmux"]

- name: Cloning oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: "~{{username}}/.oh-my-zsh"

- name: Copy git config
  template:
    src: templates/user/gitconfig.j2
    dest: ~{{username}}/.gitconfig
    owner: "{{username}}"
    mode: 0600

- name: Copying ~/.zshrc
  template:
    src: templates/shell/.zshrc.j2
    dest: ~{{username}}/.zshrc
    owner: "{{username}}"
    mode: 0600

- name: Copying ~/.tmux.conf
  template:
    src: templates/shell/.tmux.conf.j2
    dest: ~{{username}}/.tmux.conf
    owner: "{{username}}"
    mode: 0600

- name: Changing default shell to ZSH
  user:
    name: "{{username}}"
    shell: /bin/zsh

- name: Fzf setup
  command: yes | {{brew_path}}/opt/fzf/install
  args:
    creates: ~{{username}}/.fzf.zsh
