---
- name: Add {{username}} user and add it to sudo
  become: yes
  user:
    name: "{{username}}"
    state: present
    group: staff
    groups: ["staff", "admin"]
    create_home: yes

- name: Create user bin directory
  become: yes
  file:
    path: "~{{username}}/bin"
    owner: "{{username}}"
    mode: 0700
    state: directory

- name: Chown user Library
  become: yes
  file:
    path: "~{{username}}/Library"
    recurse: yes
    owner: "{{username}}"
    state: directory

- name: Set up authorized keys for {{username}}
  become: yes
  authorized_key: user={{username}} key="{{item}}"
  with_file: "{{local_public_ssh_key_path}}"

- name: Upload private key
  become: yes
  copy:
    src: "{{local_private_ssh_key_path}}"
    dest: "~{{username}}/.ssh/id_rsa"
    owner: "{{username}}"
    mode: 0600

- name: passwordless sudo commands
  become: yes
  template:
    src: templates/user/sudoers.j2
    dest: /etc/sudoers.d/{{username}}
    validate: "visudo -cf %s"
    mode: 0440

- name: Set timezone to {{timezone}}
  become: yes
  timezone:
    name: "{{timezone}}"

- name: Set a hostname
  become: yes
  command: scutil --set HostName {{hostname}}

- name: Change kern.maxfiles
  become: yes
  sysctl:
    name: kern.maxfiles
    value: "524288"
    sysctl_set: yes
    state: present
    reload: no
