---
- name: Create sudo group
  group: name=sudo state=present

- name: Add {{username}} user and add it to sudo
  user: name={{username}} state=present createhome=yes

- name: Create user bin directory
  file:
    path: "~{{username}}/bin"
    owner: "{{username}}"
    group: "{{username}}"
    mode: "700"
    state: directory

- name: Set up authorized keys for {{username}}
  authorized_key: user={{username}} key="{{item}}"
  with_file: "{{local_ssh_path}}"

- name: passwordless sudo commands
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "{{username}} ALL=(ALL) NOPASSWD:ALL"
    validate: "visudo -cf %s"
