- name: Create VSCode data directory
  file:
    path: "{{vscode_data_path}}"
    state: directory

- name: Run VSCode with docker-compose
  docker_compose:
    project_name: vscode
    definition:
      version: "3"
      services:
        vscode:
          container_name: vscode
          image: codercom/code-server
          command: "/usr/local/bin/code-server --host 0.0.0.0 --port 8080 --user-data-dir=/usr/local/var/code-server --auth password"
          volumes:
            - "{{vscode_data_path}}:/usr/local/var/code-server"
          ports:
            - "{{vscode_local_port}}:8080"
          environment:
            - "PASSWORD={{vscode_password}}"
  register: vscode_docker_output

- name: NGinx reverse proxy for VSCode
  become: true
  template:
    src: templates/nginx/site.conf.j2
    dest: /etc/nginx/sites-available/vscode.conf
    mode: "0600"
  vars:
    host: "{{vscode_remote_host}}"
    port: "{{vscode_local_port}}"

- name: NGinx config symlink
  become: true
  file:
    src: /etc/nginx/sites-available/vscode.conf
    dest: /etc/nginx/sites-enabled/vscode.conf
    state: link

- name: Restart nginx
  become: true
  service:
    name: nginx
    state: restarted
